### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by jeffvandyke** [marek-g/rust-ledger-parser#8]
Just wanted to let you know that I appreciated being able to find this package! Though basic, it seems sufficient for use in scripts, and I plan on using it. Writing data shouldn't be too hard, so I just need to find a package that can do that, or write my own function.

I hope to be able to submit pull requests for some improvement items or documentation, so thanks again for maintaining it!

**Comment by marek-g** [comment]
Thank you Jeff! It's really nice to know that this niche library can be useful to someone :)) I love to know that there are people using Rust & ledger-cli :D

Yes, it is simple, because it just fits my needs. I'm using it to generate some HTML reports with charts.

You may also be interested in my code written on top of it to calculate monthly balances. Maybe I'll cleanup the code and I'll make a crate from it some day but for now here it is:
[ledger_utils.zip](https://github.com/marek-g/rust-ledger-parser/files/3763875/ledger_utils.zip)

BTW. For writing you can use the same crate. All models implement fmt::Display trait so you can create and fill Ledger instance and print it. The output will be in correct ledger format.
